### ISSUE TITLE
Use Kubernetes Networking v1

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#139]
**Please describe the problem you have**
Currently, contour operator is using "k8s.io/api/networking/v1beta1".  The v1 package should be used instead.

**Comment by danehans** [comment]
Note that https://github.com/projectcontour/contour-operator/pull/133 added e2e test support which also uses v1beta1 for creating an ingress for the sample kuard app.

**Comment by sheetalsingala** [comment]
Can I give this a try?
What would be the effect of the change?

**Comment by danehans** [comment]
@sheetalsingala absolutely. This is a great first issue. You should no longer see the following warning message from the operator's logs when creating an instance of a `Contour`:
```
Warning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

You can run the operator locally or in-cluster and tail the logs. See the [contrib guide](https://github.com/projectcontour/contour-operator/blob/main/docs/CONTRIBUTING.md) for details on how to contribute. I'll assign you to this issue and let me know if you have  any questions.

**Comment by stevesloka** [comment]
@danehans I think that error comes from the watch Contour puts on that API resource. So until Contour deprecates out the `v1beta1` api version, that warning will stay.

**Comment by danehans** [comment]
@sheetalsingala PTAL at https://github.com/projectcontour/contour-operator/issues/139#issuecomment-741832608. @stevesloka does Contour have an issue filed for this that can be xref'd here?
