### ISSUE TITLE
Upgrade Support

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#142]
**Please describe the problem you have**
How do users upgrade from one release of Contour to another? Is this as simple as upgrading the operator? Will the upgrade be zero downtime?

/cc @Miciah

**Comment by youngnick** [comment]
Seems like right now the answers are:
- You upgrade the operator, that upgrades Contour
- This is not zero downtime, depending on the exact details of the upgrade.

**Comment by danehans** [comment]
Ensure Contour|GatewayClass|Gateway resources are reporting expected status conditions during the upgrade process.

**Comment by danehans** [comment]
> Will the upgrade be zero downtime?

As a first step in supporting upgrades, I suggest not requiring zero downtime. This issue should provide repeatable, tested upgrades from the previous release to the latest release.
