### ISSUE TITLE
Purpose of contour-operator

### ISSUE THREAD

**Issue by derekperkins** [projectcontour/contour-operator#155]
It would be nice to add a section to the main readme about the purpose of this project. I'm a contour user via direct yaml, and from my perspective, contour is already an operator itself. What sorts of workflows require something operating outside/above the contour scope? Offhand, the only one that I can think of is the initial cert creation that is deployed now via a job. Please don't take this as a criticism, I'm a very happy contour user, just interested in how this might change our usage.

**Comment by danehans** [comment]
@derekperkins thanks for the feedback. The readme includes a link to the k8s operator docs that provide additional background. Contour is a control plane for managing Envoy proxies. An operator is software that operators something, in this instance it's Contour. PTAL at the issues for the workflows that  the operator intends to support. One example use case is upgrades. The operator intends to provide a simple UI, i.e. `kubectl apply -f /my/new/version.yaml` for performing zero downtime upgrades of Contour and any of Contour's dependent resources.

> Offhand, the only one that I can think of is the initial cert creation that is deployed now via a job.

Yes, this is another use case the operator intends to support, including other cert management systems, i.e. Cert Manager. PTAL at the issues for additional use cases the operator intends to address.

> Please don't take this as a criticism, I'm a very happy contour user, just interested in how this might change our usage.

None taken at all, I'm happy that you took the time to explore the project and provide feedback. PTAL at the [contrib guide](https://github.com/projectcontour/contour-operator/blob/main/docs/CONTRIBUTING.md) and feel free to submit a PR on how to improve the docs or any other part of the project.

I'm going to close this issue. Feel free to reopen if you feel the issue requires additional discussion or if you intend on submitting a PR to improve the readme.

**Comment by derekperkins** [comment]
I've looked through the issues and don't see where the operator adds much over a standard yaml deployment today. I get that the operator is very young and I'm sure you have lots of plans for it that may not be apparent just looking at the issues. As it matures, it would definitely be helpful to list off the benefits at the top of the readme. Good luck!
