### ISSUE TITLE
Convert ClusterRole Resource to v1

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#156]
**Please describe the problem you have**
```
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
```

Convert `ClusterRole` resources to v1.

**Comment by danehans** [comment]
This should be as simple as updating the API group reference in "config/rbac/auth_proxy_client_clusterrole.yaml" and run `make example`. FYI @sheetalsingala if you're interested. If so, assign yourself.

**Comment by krishnaindani** [comment]
@danehans Is this issue available? If so I would like to work on this.

**Comment by danehans** [comment]
@krishnaindani I've assigned you the issue. Let me know if you have any questions.

**Comment by krishnaindani** [comment]
> @krishnaindani I've assigned you the issue. Let me know if you have any questions.

Sure. Thank you

**Comment by krishnaindani** [comment]
we need to change [this](https://github.com/projectcontour/contour-operator/blob/main/config/rbac/auth_proxy_client_clusterrole.yaml#L1) apiVersion here to use `rbac.authorization.k8s.io/v1` and run the `make example` then. Did I understand correctly? @danehans

**Comment by danehans** [comment]
@krishnaindani that should do it. I suggest running `make check`, `make test-e2e` and `make test-examples` to ensure all tests pass. You'll need a running cluster for the last two tests (`make local-cluster` if needed).

**Comment by krishnaindani** [comment]
> @krishnaindani that should do it. I suggest running `make check`, `make test-e2e` and `make test-examples` to ensure all tests pass. You'll need a running cluster for the last two tests (`make local-cluster` if needed).

Sounds good. Thank you!! I Will make sure all tests pass.
