### ISSUE TITLE
Extend NetworkPublishing API

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#159]
Extend the NetworkPublishing API to support the following use cases:
- Set the `awsLbBackendProtoAnnotation: tcp` annotation only if the provider of `LoadBalancerServicePublishingType` is AWS.
- Add support to `NodePortServicePublishingType` to specify: 1) auto (default) or manual port allocation. If manual, provide fields to specify the desired http/https nodePorts (30080 default for http and 30443 default for https).

**Comment by danehans** [comment]
xref: https://github.com/projectcontour/contour-operator/pull/151
xref: https://github.com/projectcontour/contour-operator/pull/152

**Comment by stevesloka** [comment]
> Support to NodePortServicePublishingType to specify: 1) auto (default) or manual port allocation. If manual, provide fields to specify the desired http/https nodePorts (30080 default for http and 30443 default for https).

This implies the `default` by choosing option #1 is ports `30080` & `30443`. Just want to confirm that's the thought, in my head, `auto` implies that k8s is specifying the ports which is the default unless you specify the ports (e.g. `manual`).

**Comment by danehans** [comment]
Fixed by:
- https://github.com/projectcontour/contour-operator/pull/367 (proxy proto support)
- #151 and #152 for NodePortService support.
