### ISSUE TITLE
Fix test-examples Make Target

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#160]
"Sending http request to http://local.projectcontour.io" iterates forever when the example deployment fails from `make test-examples`. The curl test should fail after a specified number of attempts or a timeout is reached.

**Comment by danehans** [comment]
This is a good first issue for anyone interested.

**Comment by sheetalsingala** [comment]
Hi @danehans, I see that there is already [timeout](https://github.com/projectcontour/contour-operator/blob/main/hack/test-examples.sh#L24) for `waitForHttpResponse`.
Am I looking at the right thing here?

**Comment by danehans** [comment]
@sheetalsingala PTAL at https://github.com/projectcontour/contour-operator/pull/162 that includes the fix (among other improvements).
