### ISSUE TITLE
testing: Run a nightly Contour install CI job

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour-operator#194]
As the operator matures, it's important for us to be confident that Contour controller changes don't break the operator.

To this end, this issue covers:
- setting up some sort of CI job that runs on a schedule (probably daily to start with, but could be more frequent if it's not too expensive)
- the job must test that `projectcontour/contour:main` and `projectcontour/contour-operator:main` work together.
- The first phase is to test that an install ( and possibly removal) works; upgrades are left as a future exercise, although we acknowledge that a `previous release -> main` upgrade check will be immensely valuable.
- The exact nature of the tests are left as an exercise for the implementer; something like `contour`'s integration tests (that actually verify at least basic Contour functionality) would be very useful as well.

**Comment by danehans** [comment]
fixed by https://github.com/projectcontour/contour-operator/pull/206.
