### ISSUE TITLE
Add option for Contour's `--ingress-class-name`

### ISSUE THREAD

**Issue by eplightning** [projectcontour/contour-operator#228]
**Please describe the problem you have**

Currently there's no way to specify Contour's `--ingress-class-name` flag (https://projectcontour.io/docs/main/config/annotations/#ingress-class) when using the operator. 

This makes it impossible to deploy multiple instances of Contour which serve different subsets of ingresses (without deploying other Contour instances manually of course).

I might be missing something but I can't see any way of specifying it at this moment.

**Comment by nak3** [comment]
This is a blocker of contour operator for Knative.

**Comment by sunjayBhatia** [comment]
Sounds like we can maybe just add this configuration field in the top level `ContourSpec` alongside the Gateway class reference? https://github.com/projectcontour/contour-operator/blob/5aaf14eeb2a21606502406c13ceba000ff64ff86/api/v1alpha1/contour_types.go#L61-L92

If theres no objections to that placement I can put up a quick PR

**Comment by stevesloka** [comment]
I think that works @sunjayBhatia. We'll need to have logic to check for duplicate ingress class names as well as duplicate gatewayclass names but can be a seperate PR (if not already there).

**Comment by sunjayBhatia** [comment]
Oh actually before we do this how do you see this interfering with the `IngressClass` work as well: https://github.com/projectcontour/contour/issues/2146

Seems like this request is for the Ingress v1beta1 feature and the `--ingress-class-name` flag is already public, but since it's not exposed on the operator this is a chance to have a nicely defined API here with the differences between Ingress v1beta1 and Ingress v1

**Comment by danehans** [comment]
xref: https://github.com/projectcontour/contour-operator/issues/240

**Comment by danehans** [comment]
@eplightning @nak3 now that this issue is resolved, the operator should support the Knative use case. Can you please confirm and provide an update to this issue?

**Comment by eplightning** [comment]
Just tested it out, I can now create multiple Contour instances with different `--ingress-class-name` flags using the Operator.

It's enough for my use case. I'm not an expert on Knative but it should be enough there as well.

Thanks
