### ISSUE TITLE
CI fails when run against release branches

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour-operator#230]
**What steps did you take and what happened:**
- created a PR with a cherry-pick of a bug fix into the `release-1.13` branch.
- Got a CI failure: https://github.com/projectcontour/contour-operator/pull/229/checks?check_run_id=2006878783

Looks like the CI code (`make verify-image` and maybe more) need to be updated to handle branches where the image tags are not `main`.

**What did you expect to happen:**
- CI to pass

**Comment by stevesloka** [comment]
Duplicate of #169?

**Comment by skriss** [comment]
Yep, closing.
