### ISSUE TITLE
Incorrect Listener Hostname Validation

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#234]
**Please describe the problem you have**
Currently, a gateway will fail if a listener uses a wildcard in the hostname, i.e. "*.foo.com". Note that a wildcard on its own will succeed. Per the Gateway spec, validation should be updated to allow wildcards in hostnames.

**Comment by danehans** [comment]
Removing milestone until the community achieves a consensus on the Gateway API implementation plan.

**Comment by skriss** [comment]
This is now a concern for Contour proper, closing the issue here.
