### ISSUE TITLE
Update EnsureX() Functions to Support Different Object Types

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#244]
**Please describe the problem you have**
Currently, the Contour type is used for ensureX() functions. These functions need to be updated to support the Gateway type since certain gateway information is used to configure resources. The following are a few specifics related to these functions:

- A resource should use the gateway ns/name instead of contour.spec.namespace name when the provided object in of type Gateway.
- A resource should use the gateway owning labels instead of contour owning labels when the provided object in of type Gateway.
- Others?

**Comment by skriss** [comment]
removing from 1.15 milestone, @danehans pls update as appropriate.

**Comment by danehans** [comment]
Closing since Gateway API support is being migrated to contour.
