### ISSUE TITLE
main is broken 

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour-operator#249]
https://github.com/projectcontour/contour-operator/runs/2059896873?check_suite_focus=true

**Comment by danehans** [comment]
Scheduled CI runs are now consistently passing. For example:
https://github.com/projectcontour/contour-operator/actions/runs/634571122
https://github.com/projectcontour/contour-operator/actions/runs/634450047
https://github.com/projectcontour/contour-operator/actions/runs/634355813
