### ISSUE TITLE
Flaky CI Tests

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#251]
[CI jobs](https://github.com/projectcontour/contour-operator/actions/workflows/prbuild.yaml) are intermittently failing. I'm unable to reproduce the flake, but I believe it's related to updating a Contour from defaults to Gateway-enabled in `test_suite.go`. This issue may be resolved by https://github.com/projectcontour/contour-operator/pull/250. In the meantime, I suggest disabling this portion of the test since the e2e tests cover Gateway support.

xref: https://github.com/projectcontour/contour-operator/issues/249

**Comment by danehans** [comment]
If converting an existing Contour to Gateway-API enabled is flaky, maybe doc the API field as immutable.

**Comment by danehans** [comment]
xref: https://github.com/projectcontour/contour-operator/issues/218 could also be the issue.

**Comment by danehans** [comment]
Removing milestone until the community achieves a consensus on the Gateway API implementation plan.

**Comment by skriss** [comment]
Still seeing this in `suite_test.go`, e.g. https://github.com/projectcontour/contour-operator/runs/2381643663?check_suite_focus=true.

I'll look into this some more and see if I can figure out a fix. May be a matter of adding some retries around updates, or switching to using `Patch` instead.
