### ISSUE TITLE
List instead of Get Gateway CRDs

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#270]
**Please describe the problem you have**
With https://github.com/projectcontour/contour-operator/pull/261 the operator gets each CRD required for Gateway API support. To reduce API calls, list the CRDs and iterate over the items to ensure each required Gateway CRD exists.

**Comment by stevesloka** [comment]
This is how Contour does this check today: https://github.com/projectcontour/contour/blob/main/internal/k8s/clients.go#L120-L131
