### ISSUE TITLE
Remove Logging for "Skipped..." Operations

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#28]
**Please describe the problem you have**
The operator logs many events when an operation is being skipped. Although this is nice for early development, it should be removed to reduce noise as the operator matures.

xref: https://github.com/projectcontour/contour-operator/pull/21#discussion_r489086428

/cc @Miciah

**Comment by Miciah** [comment]
The logging is useful during development, so we won't remove this for v1alpha1.

Alternatively, we might want to keep this logging even after alpha but set the logging level to "debug" (or equivalent).
