### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference, on Aarch64

### ISSUE THREAD

**Issue by advancedwebdeveloper** [projectcontour/contour-operator#286]
Hello.

Citation from https://gist.github.com/advancedwebdeveloper/c56618fbfed8f6b987a483d1e9428e79 :

> Test Panicked
>   runtime error: invalid memory address or nil pointer dereference
>   /usr/local/go/src/runtime/panic.go:212

. I have applied such a patch:
https://gist.github.com/advancedwebdeveloper/b5f1c2acb2a29aa52ee8a0aa1a80fa1f
.

Some tests surely fail cause of misconfigured dependecies and virtual infrastructure - but that does explain why non-acceptable memory happened.

Here is my environment:

> $ lscpu
> Architecture:                    aarch64
> CPU op-mode(s):                  64-bit
> Byte Order:                      Little Endian
> CPU(s):                          96
> On-line CPU(s) list:             0-95
> Thread(s) per core:              1
> Core(s) per socket:              48
> Socket(s):                       2
> NUMA node(s):                    2
> Vendor ID:                       Cavium
> Model:                           1
> Model name:                      ThunderX 88XX
> 
> $ go version
> go version go1.16.2 linux/arm64
> 
> $ go env
> GO111MODULE=""
> GOARCH="arm64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="arm64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/usr/local/go"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
> GOVCS=""
> GOVERSION="go1.16.2"
> GCCGO="gccgo"
> AR="ar"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> GOMOD="/home/oceanfish81/contour-operator/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2577297875=/tmp/go-build -gno-record-gcc-switches"
> 
> $ gcc --version
> gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
> 
> $ ld --version
> GNU ld (GNU Binutils for Ubuntu) 2.34
> 

@ianlancetaylor, any advices on tracking down the cause?

**Comment by danehans** [comment]
@advancedwebdeveloper thanks for opening the issue. The tests are failing to create the k8s control-plane because it can't find the etcd bin:
```
2021-03-30T21:39:01.327Z	ERROR	controller-runtime.test-env	unable to start the controlplane	{"tries": 0, "error": "fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory"}
```

This appears to be a doc bug for the [contrib guide](https://github.com/projectcontour/contour-operator/blob/main/docs/CONTRIBUTING.md). Can you [install kubebuilder](https://book.kubebuilder.io/quick-start.html) and then verify the presence of the etcd bin (`stat /usr/local/kubebuilder/bin/etcd`)?
