### ISSUE TITLE
RFE: Move Contour and Envoy image configuration options to Contour.Spec from command line

### ISSUE THREAD

**Issue by nak3** [projectcontour/contour-operator#299]
**Please describe the problem you have**

I would like to request that `--contour-image` and `--envoy-image` command options:
https://github.com/projectcontour/contour-operator/blob/7e5ae24ae7234ea9d539ff6468c7c4623c045b9c/cmd/contour-operator.go#L34-L37
should be moved in `ContourSpec`. https://github.com/projectcontour/contour-operator/blob/7e5ae24ae7234ea9d539ff6468c7c4623c045b9c/api/v1alpha1/contour_types.go#L61

- use case 1)
The configuration should be centralized.

- use case 2)
When we deployed multiple `Contour` CR, we have to use same images among all Contour CRs. It is not possible to test a new Contour or Envoy image by one of Contour CRs.

**Comment by danehans** [comment]
@nak3 PTAL at https://github.com/projectcontour/contour-operator/issues/55 for background on the current version management approach. I need to think through the different approaches for supporting the blue/green upgrades. I'll put together some ideas and update this issue. cc: @Miciah

**Comment by stevesloka** [comment]
Hey @nak3, can you explain a bit more about case 2 above? Are you wanting to smoke test the new version before rolling it out? Or do you want to stage the rollouts such that you don't upgrade all your instances at the same time?

**Comment by nak3** [comment]
@danehans Sure! Thank you.

@stevesloka I wanted it for a smoke test originally. When I fixed an operator bug, I wanted to verify the Contour image quickly but that needs upgrade of all Contour images.
With said, I believe that there are some users who want to stage the rollouts.

**Comment by nak3** [comment]
I understand. Thank you. I am closing this.
