### ISSUE TITLE
Expand e2e to Support Cloud-Specific Features

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#321]
**Please describe the problem you have**
Although kind is great for testing most features, it can not provide full e2e coverage due to cloud-specific features provided by the Contour custom resource. The e2e tests should support running on kind and standard k8s clusters.

**Comment by sunjayBhatia** [comment]
Sounds like we should have a plan for setting up a cloud provider k8s cluster for running tests against, this will come up similarly in other domains (like w/ running Windows worker nodes, which kind can't do)

**Comment by youngnick** [comment]
Having a plan/set of requirements for this would also be handy for being able to run the controller's e2e tests against a cloud cluster instead of kind.
