### ISSUE TITLE
Option to pass loadBalancerIP to Contour

### ISSUE THREAD

**Issue by BostjanBozic** [projectcontour/contour-operator#326]
**Please describe the problem you have**
It would be great to have an option to pass loadBalancerIP parameter to Contour.

This would help in a workflow, where you reserve public IP on cloud provider for Contour, configure DNS and then you can pass it in Contour configuration.

Currently only `type` parameter is supported in `providerParameters`, it would be great if this can be extended to include `loadBalancerIP`.

**Comment by BostjanBozic** [comment]
This use case has been resolved by https://github.com/projectcontour/contour-operator/pull/336

**Comment by jberger** [comment]
As far as I can tell, #336 doesn't allow adding generic loadBalancerIP to the contour/envoy, it only allows you to do so if you're using a specific provider. I'm running bare metal using metallb and the ability to just set loadBalancerIP on the service would be much appreciated. Am I wrong, is it possible?

**Comment by youngnick** [comment]
@jberger, sorry for the delay here. You're right, the loadbalancerIP support here is only for specific providers. Would you mind opening an issue with your requirement, then we can see what we can do?
