### ISSUE TITLE
Use semantic equality for object comparisons

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour-operator#35]
**What steps did you take and what happened:**

We should prefer to use api-machinery semantic equality to compare objects.

https://godoc.org/k8s.io/apimachinery/pkg/api/equality

https://github.com/projectcontour/contour/issues/2995

**Comment by jpeach** [comment]
xref #45

**Comment by Miciah** [comment]
We're already using the semantic equality package from apimachinery in https://github.com/projectcontour/contour-operator/pull/31 and https://github.com/projectcontour/contour-operator/pull/33, and we're not using go-cmp or similar anywhere, so I believe this issue is resolved.
