### ISSUE TITLE
define affinity, tolerations for envoy pods

### ISSUE THREAD

**Issue by r0bj** [projectcontour/contour-operator#362]
**Please describe the problem you have**
[A clear, concise, description of the problem you are facing. What is the _problem_ that feature X would solve for you?]

I would like to deploy envoy to subset of my nodes with specific taints. It would be useful to have ability to set affinity, tolerations for envoy pods (maybe also for contour pods).

**Comment by danehans** [comment]
@r0bj thanks for the creating issue. I like the idea of adding placement support for envoy and contour pods. Is this a feature that you can help develop? Do you mind updating this issue to be focused on this issue and create separate issues for the other requested features?

**Comment by danehans** [comment]
> I would like to deploy envoy to subset of my nodes with specific taints. It would be useful to have ability to set affinity, tolerations for envoy pods (maybe also for contour pods).

xref https://github.com/projectcontour/contour-operator/pull/373 for envoy pod placement.

**Comment by r0bj** [comment]
I updated this issue to cover only placement support.

**Comment by r0bj** [comment]
It could be probably combined with supporting pod template: https://github.com/projectcontour/contour-operator/issues/378

**Comment by danehans** [comment]
> It could be probably combined with supporting pod template: #378

I prefer that issues are as specific as possible, so let's not combine.

@r0bj I believe https://github.com/projectcontour/contour-operator/pull/373 resolves this issue. If so, please confirm and close this issue. If not, please let us know what else is needed.

**Comment by r0bj** [comment]
@danehans Thanks!
