### ISSUE TITLE
update example operator deployment to support arm64

### ISSUE THREAD

**Issue by vchrisb** [projectcontour/contour-operator#375]
The image currently used for `kube-rbac-proxy` is `gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0`.
https://github.com/projectcontour/contour-operator/blob/main/examples/operator/operator.yaml#L6531 

This image is published by kubebuilder project rather than the kube-rbac-proxy project and is not multi-arch.

kube-rbac-proxy project is publishing to `quay.io/brancz/kube-rbac-proxy` and these images are multi-arch.

Updating the deployment to use kube-rbac-proxy v0.6.0+ from `quay.io/brancz/kube-rbac-proxy` would allow using the operator on arm64.

**Comment by danehans** [comment]
Fixed by https://github.com/projectcontour/contour-operator/pull/376
