### ISSUE TITLE
Support for custom envoy, countour images

### ISSUE THREAD

**Issue by r0bj** [projectcontour/contour-operator#380]
**Please describe the problem you have**
[A clear, concise, description of the problem you are facing. What is the _problem_ that feature X would solve for you?]

It would be useful to have ability to set custom images for envoy and contour. Especially that default images are from docker hub (rate limiting). And also in some organizations there are policies that enforce using only images from local repositories.

**Comment by sunjayBhatia** [comment]
images can be customized with these flags: https://github.com/projectcontour/contour-operator/blob/c72b69263e6845c4f168392d54b3cdeb2264dca0/cmd/contour-operator.go#L34-L37

**Comment by r0bj** [comment]
@sunjayBhatia thanks! It would be probably easier to have those options in contour CRD spec but it's good that we have it.

**Comment by danehans** [comment]
@r0bj we made a deliberate decision to use CLI flags instead of exposing Contour/Envoy image flags in the API. PTAL at #55 for additional background. Feel free to reopen #55 to address your use case or state your case for changing the current approach.
