### ISSUE TITLE
Deprecate GatewayClass and Gateway Controllers

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#389]
**Please describe the problem you have**
These controllers are being implemented in Contour. When Gateway API support in Contour reaches feature parity with the operator, deprecate these controllers.

Functionality needed for feature parity:
- [ ] Support [multiple gateways](https://github.com/projectcontour/contour/issues/3825).
- [ ] e2e and integration testing, [xref](https://github.com/projectcontour/contour/issues/3705).
- [ ] Configurability, [xref](https://github.com/projectcontour/contour/issues/3545).
- [ ] Others?

**Comment by sunjayBhatia** [comment]
this has been completed
