### ISSUE TITLE
Operator should configure Contour with gateway controller name

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour-operator#400]
Contour now requires the gateway controller string to be set in its config when using Gateway API

Currently, Contours deployed by the operator fail with:

```
contour: error: invalid Contour configuration: invalid Gateway parameters specified: controllerName required, try --help
```

We also need to see if we need to start removing some of the gateway/gateway class controller logic in the operator now that Contour itself has a gateway and gateway class controller

**Comment by youngnick** [comment]
Investigating this, I have a patch that fixes this problem, but a further change in Contour has made GatewayClasses with non-nil parametersRef invalid, this should be ignored. Working on a patch for that now, and I'll log an issue in Contour to track that work.

Once those two things are fixed, I think we will need to cut a .1 release to fix this, for both products.
