### ISSUE TITLE
Validation of IngressClass existence can break existing uses of the operator

### ISSUE THREAD

**Issue by dprotaso** [projectcontour/contour-operator#403]
**What steps did you take and what happened:**

Knative configures two contour instances - one for external and internal traffic. We use `ingressClassName` as a way to designate between the two instances.

When using this setup with the operator & contour 1.17 it requires us to create an `IngressClass` object just to satisfy the existence check added by https://github.com/projectcontour/contour-operator/pull/388 

**What did you expect to happen:**

I can create these two contour instances without the need to create an `IngressClass` object

**Anything else you would like to add:**

Knative tracking issue: https://github.com/knative-sandbox/net-contour/issues/549

**Environment:**

- Software version: Contour 1.17
- Kubernetes version: (use `kubectl version`): any
- Kubernetes installer & version: any
- Cloud provider or hardware configuration: GKE/Kind
- OS (e.g. from `/etc/os-release`): any

**Comment by sunjayBhatia** [comment]
Worth noting that Contour standalone (no operator) does *not* require an IngressClass resource to exist (bc in practice it is not used for anything) when configured with the IngressClass name flag so the Operator is adding an additional restriction Contour does not
