### ISSUE TITLE
When Contour removes Gateway Name/Namespace from configuration, operator should stop using it

### ISSUE THREAD

**Issue by sunjayBhatia** [projectcontour/contour-operator#411]
Once https://github.com/projectcontour/contour/pull/3881 is merged, the Operator should no longer configure a Gateway name/namespace in the Contour configmap

**Comment by sunjayBhatia** [comment]
Now that I think about it, might be required to move this to 1.19 so we don't re-break the operator/contour

right now it works ok having multiple contours b/c we're still passing the gateway name/namespace so a contour reconciles a single gateway

**Comment by skriss** [comment]
Closed by #422 (@sunjayBhatia feel free to reopen if there was anything else to do here)
