### ISSUE TITLE
test-example-linux job occasionally hangs

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour-operator#419]
E.g. https://github.com/projectcontour/contour-operator/runs/3197940834?check_suite_focus=true

Seems to be in the middle of the HTTP request loop.

Can try adding `curl`'s `--max-time` flag to start.

**Comment by sunjayBhatia** [comment]
@skriss when youre back, I attached a PR that should close this, but feel free to take it over if you had something else in mind

**Comment by skriss** [comment]
:+1: LGTM, hopefully that resolves it
