### ISSUE TITLE
ongoing test-e2e-linux and test-example-linux flakes

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour-operator#433]
We are still seeing sporadic test flakes in the `test-e2e-linux` and `test-example-linux` jobs, e.g.:

https://github.com/projectcontour/contour-operator/actions/runs/1181920017
https://github.com/projectcontour/contour-operator/actions/runs/1180861979
https://github.com/projectcontour/contour-operator/actions/runs/1180638912

It'd be really nice to continue to try to get rid of these.

**Comment by sunjayBhatia** [comment]
example tests seem a lot more stable since we moved them to go 🤞🏽

**Comment by skriss** [comment]
And seems like maybe that data race you fixed cleaned up the E2E's too

**Comment by skriss** [comment]
I'm going to close this out, things have been pretty stable for awhile now, nice work @sunjayBhatia!
