### ISSUE TITLE
Option to configure `enableExternalNameService`

### ISSUE THREAD

**Issue by kvmware** [projectcontour/contour-operator#437]
Recently, `enableExternalNameService` is default being set to `false` to mitigate https://github.com/kubernetes/kubernetes/issues/103675. This is creating a breaking change for Knative. It would be nice to be able to use the operator which we use in our Knative serving e2e tests to override this for now, until we move forward with one of the paths below.

For more context https://github.com/knative/serving/issues/11821.

**Comment by youngnick** [comment]
I think this is fair, we should do this.
