### ISSUE TITLE
Create an Equality Package

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#45]
**Please describe the problem you have**
Currently `Contour` equality is being duplicated across managed dependent resources. Create a pkg that performs the equality matching that can be leveraged across the project.

**Comment by jpeach** [comment]
What I would suggest here is to write comparison functions that you can provide to `conversion.EqualitiesOrDie`

```Go
func Semantic() conversion.Equalities {
    e := Equalities{equalities.Semantic} // take base equalities from kubernetes

    e.AddFuncs(
        operatorCompareJob,
        operatorCompareDeployment,
    )

    return e
}
```

xref #47

**Comment by danehans** [comment]
Equality pkg created [here](https://github.com/projectcontour/contour-operator/tree/main/internal/equality).
