### ISSUE TITLE
Add Proxy Protocol Support

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#49]
**Please describe the problem you have**
Currently, the Envoy `Service` is annotated with "service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp" that places the AWS ELB in TCP mode. This causes the ELB to masquerade the client IP. Adding proxy protocol support will allow the client IP to be preserved for ELB'd connections.

Another approach is to use AWS NLB instead of ELB since NLB natively preserves client IPs.

/cc @jpeach @stevesloka @michmike 

xref: [examples/contour/02-service-envoy](https://github.com/projectcontour/contour/blob/main/examples/contour/02-service-envoy.yaml)

**Comment by jpeach** [comment]
Maybe need to look more closely at AWS deployment options. I think the operator should deal with low-level stuff like what annotations to make and the user should specify some sort of high-level AWS-specific goals.

**Comment by Miciah** [comment]
xref:  https://github.com/projectcontour/contour-operator/issues/70

**Comment by stevesloka** [comment]
I think switching over to NLBs is fine, but we're not an `AWS` only project. We might need to think about having supported configmaps which outline the various annotations or code in to the project support for whatever environment we're deploying into.

**Comment by Miciah** [comment]
AFAIK the other major platforms provide source preservation.  At least Azure and GCP do.  AWS's ELBs are the odd one out here.

**Comment by jpeach** [comment]
> I think switching over to NLBs is fine, but we're not an `AWS` only project. We might need to think about having supported configmaps which outline the various annotations or code in to the project support for whatever environment we're deploying into.

Right. This was what the kustomize PR #2474 did.

Pretty sure that NLB works out cheaper https://aws.amazon.com/elasticloadbalancing/pricing/

**Comment by danehans** [comment]
xref contour nlb docs: https://projectcontour.io/guides/deploy-aws-nlb/

**Comment by danehans** [comment]
xref contour proxy protocol support docs: https://projectcontour.io/guides/proxy-proto/
