### ISSUE TITLE
Is it possible to use GatewayClass to create Contour instances directly in the future?

### ISSUE THREAD

**Issue by lou-lan** [projectcontour/contour-operator#500]
As the title suggests, I'm not quite sure what the guidance for implementing the gateway api is, but it would certainly simplify the process.

**Comment by sunjayBhatia** [comment]
https://github.com/projectcontour/contour/blob/main/design/automated-provisioning-design.md

This design document should explain what our current direction is around gateway api and automated installs of contour

**Comment by youngnick** [comment]
In short, it is not yet, but it will be, but there are some side-effects for the operator. The details are in the document @sunjayBhatia linked above, please check them out.
