### ISSUE TITLE
Create Image Repo

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#6]
**Please describe the problem you have**
As I work on contour-operator, I’ve been pushing the image to my own repo. An image repo should be created in the Docker Hub projectcontour org for this project.

/assign @jpeach

**Comment by stevesloka** [comment]
Here ya go @danehans: https://hub.docker.com/r/projectcontour/contour-operator

Contour uses Github Actions to push PRs as a `main` tag for each merge. Do you want to start with that workflow? We bake the creds into secrets in the CI tool.

**Comment by danehans** [comment]
@stevesloka thanks for creating the image repo.

> Contour uses Github Actions to push PRs as a main tag for each merge. Do you want to start with that workflow? We bake the creds into secrets in the CI tool.

Yes, that would be much appreciated.

**Comment by Miciah** [comment]
I'm closing this issue because it has been resolved with the creation of the https://hub.docker.com/r/projectcontour/contour-operator repository, and I have opened https://github.com/projectcontour/contour-operator/issues/80 to track automating pushing a new tag as suggested in https://github.com/projectcontour/contour-operator/issues/6#issuecomment-683951165.

**Comment by danehans** [comment]
@stevesloka I do not have permissions to push an image to projectcontour/contour-operator:
```
$ make docker-build docker-push IMG=docker.io/projectcontour/contour-operator:latest
...
The push refers to repository [docker.io/projectcontour/contour-operator]
f397c11f1461: Preparing 
84ff92691f90: Preparing 
d72a74c56330: Preparing 
denied: requested access to the resource is denied
make: *** [docker-push] Error 1
```
Do you have permissions to push the image? If so, can you pull the latest contour-operator changes and build/push the image until we have the GH Action created? I would like to update the [image reference](https://github.com/projectcontour/contour-operator/blob/main/config/manager/kustomization.yaml#L7) from my personal  repo to the project's repo.

**Comment by stevesloka** [comment]
I can't push either, need the bot creds setup. @youngnick  can you share those creds to create some dockerhub creds for this repo private on slack?

**Comment by danehans** [comment]
The issue is being reopened due to https://github.com/projectcontour/contour-operator/issues/6#issuecomment-716865925. Waiting for @youngnick to confirm that maintainers have creds to push the `contour-operator` image to `docker.io/projectcontour/contour-operator:latest`.

**Comment by danehans** [comment]
I verified `docker.io/projectcontour/contour-operator:latest` works in https://github.com/projectcontour/contour-operator/pull/81 so I'm now closing this issue. Thanks @youngnick for getting the image pushed.

**Comment by youngnick** [comment]
I've pushed an initial build just using my credentials for now. I'll look at the best way to add the auto-building using the `projectcontourbuilder` bot.
