### ISSUE TITLE
Implement Contour Status Sub Resource

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#60]
**Please describe the problem you have**
Status of `Contour` is currently not implemented. Implement a basic level of status that surfaces an available condition based upon the availability of Contour/Envoy pods, etc..

__Note:__ Other conditions should be implemented post v1alpha1.

xref: [HTTProxy Status Conditions (Detailed)](https://github.com/projectcontour/contour/blob/main/apis/projectcontour/v1/detailedconditions.go)

/cc @jpeach @Miciah

**Comment by Miciah** [comment]
Example output:
```
$ kubectl get contour/foo -n projectcontour -o yaml
metadata:
  namespace: projectcontour
  name: foo
spec:
  replicas: 2
...
status:
  contourReplicasAvailable: 2
  envoyReplicasAvailable: 6
  certificatesGenerated: "true"
  ...
```
