### ISSUE TITLE
Add PR action to run tests

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour-operator#68]
**Please describe the problem you have**

Add a PR-scoped Github Action to run unit tests and kubebuilder integration tests.

**Comment by jpeach** [comment]
You might be able to yank some scripting for this from the contour project.

**Comment by Miciah** [comment]
Looks like we could re-use the CI logic here:  https://github.com/projectcontour/contour/tree/main/_integration/testsuite

@jpeach, can you clarify what you mean by "kubebuilder integration tests"?

**Comment by jpeach** [comment]
> @jpeach, can you clarify what you mean by "kubebuilder integration tests"?

I just meant "make test"
