### ISSUE TITLE
Incorporate projectcontour/contour-operator in to the Contour release process

### ISSUE THREAD

**Issue by Miciah** [projectcontour/contour-operator#71]
We would like to incorporate contour-operator into [the Contour release process](https://projectcontour.io/resources/release-process/).  

Goals:

* Enable us to make a new projectcontour/contour-operator release shortly after, or in tandem with, each new projectcontour/contour release.  
* Keep projectcontour/contour and projectcontour/contour-operator releases in sync as much as possible.  
* Automate the contour-operator release process.  

To this end, we propose the following changes:

* Define a GitHub action that triggers on each new projectcontour/contour release.  This action would open a PR in projectcontour/contour-operator to update `config/manager/kustomization.yaml` to reference the new Contour image.  CI would then automatically verify contour-operator with the new Contour release.  The PR description could include instructions for reviewing the PR and completing the projectcontour/contour-operator release.  

* Update the Contour release process with an additional/follow-up step to do a manual review of the automatically created PR.  If the PR is passing tests with the new Contour release and there are no outstanding issues in projectcontour/contour-operator, a maintainer would merge the PR and follow the instructions in the PR's description to create and push a tag, which would produce a new contour-operator release.  

This would be very nice to have for v1alpha1, but it is more a stretch goal than a blocking issue.  

---

As a long-term goal once contour-operator is more mature, it would make sense to use projectcontour/contour-operator to set up Contour in projectcontour/contour CI jobs, but we can track that as a separate issue.  

---

@jpeach, @stevesloka, does this approach seem feasible to you?

**Comment by stevesloka** [comment]
Sounds good to me @Miciah! At a minumim we can write up the release notes on how to deploy the operator and follow along manually until all the automation bits are up: https://projectcontour.io/resources/release-process/

**Comment by jpeach** [comment]
Maybe we need to think more about this. If users install the operator, then they no longer have to upgrade Contour, but they have to upgrade the operator instead. If upgrading Contour is the same thing as upgrading the operator, then the operator won't necessarily be able to give a good feedback UX on the upgrade process. If this is the approach, then it's hard for me to see how you could do a rollback if an upgrade turns out to be a bad idea. I'm sure that other operators have similar concerns; is there prior art in this area that e could learn from?

**Comment by danehans** [comment]
> If upgrading Contour is the same thing as upgrading the operator, then the operator won't necessarily be able to give a good feedback UX on the upgrade process.

@jpeach this level of status is not implemented in [PR 91](https://github.com/projectcontour/contour-operator/pull/91), but would be post v1alpha1. See [version-reporting-during-an-upgrade](https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md#version-reporting-during-an-upgrade) and [this example implementation](https://github.com/openshift/cluster-ingress-operator/blob/master/pkg/operator/controller/status/controller.go). Upgrade/Downgrade/Rollback is managed by a separate operator such as OLM. See [here](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/how-to-update-operators.md) for additional details on how OLM manages operator versions. When you have a moment, PTAL at these references and share your thoughts.

xref: https://github.com/projectcontour/contour-operator/issues/88

**Comment by jpeach** [comment]
> > If upgrading Contour is the same thing as upgrading the operator, then the operator won't necessarily be able to give a good feedback UX on the upgrade process.
> 
> @jpeach this level of status is not implemented in [PR 91](https://github.com/projectcontour/contour-operator/pull/91), but would be post v1alpha1. See [version-reporting-during-an-upgrade](https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md#version-reporting-during-an-upgrade) and [this example implementation](https://github.com/openshift/cluster-ingress-operator/blob/master/pkg/operator/controller/status/controller.go). Upgrade/Downgrade/Rollback is managed by a separate operator such as OLM. See [here](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/how-to-update-operators.md) for additional details on how OLM manages operator versions. When you have a moment, PTAL at these references and share your thoughts.

OK, so OLM is responsible for the contour-operator CRD (and the contour CRDs too?)? That solves the chicken & egg problem :)

**Comment by danehans** [comment]
> OK, so OLM is responsible for the contour-operator CRD (and the contour CRDs too?)?

@jpeach the operator is responsible for the Contour CRD. A different operator such as OLM is responsible for a separate CRD, i.e. `ClusterOperator`, that represents configuration/status of contour-operator and other operators it manages. This separate operator is responsible for surfacing status conditions through the separate CRD. For example:
```
$ kubectl get clusteroperator/contour -o yaml
apiVersion: myCrdVersion1
kind: ClusterOperator
...
status:
  conditions:
  - message: operator has minimum availability
    reason: MinimumAvailability
    status: "True"
    type: Available
  - message: operator is upgrading from v1.11 to v1.12
    reason: UpgradeInProgress
    status: "True"
    type: Progressing
  - message: operator requests 2 replicas, but only 1 is available.
    reason: ReplicasUnavailable
    status: "True"
    type: Degraded
```

Does this make sense?

**Comment by danehans** [comment]
> As a long-term goal once contour-operator is more mature, it would make sense to use projectcontour/contour-operator to set up Contour in projectcontour/contour CI jobs, but we can track that as a separate issue.

I created https://github.com/projectcontour/contour/issues/3165 to track this issue.

**Comment by danehans** [comment]
This Issue is fixed by the following commits:
- https://github.com/projectcontour/contour-operator/commit/7c77d29048e971b7b4f111c344a819cb349c5eaf
- https://github.com/projectcontour/contour-operator/commit/6e65a251debf4fde16e3e3f6f58193416bc6b702
- https://github.com/projectcontour/contour-operator/commit/7e5d1f300ca7b01bf5d18bc8e5db0c38c63af9f3
