### ISSUE TITLE
Create a GitHub action to automate updating the operator image

### ISSUE THREAD

**Issue by Miciah** [projectcontour/contour-operator#80]
Add a Github actions to update the `main` tag at https://hub.docker.com/r/projectcontour/contour-operator after each merge.  

We need to verify that CI has the necessary credentials.  

Tasks:
- [x] Build & Push `:main` image
- [ ] Build & Push tagged image

xref: https://github.com/projectcontour/contour-operator/issues/6#issuecomment-683951165

**Comment by youngnick** [comment]
I propose the same setup as we have for `projectcontour/contour` - each commit to main will build a new `:main` image, and a release will build a new tagged image with the release version, and update `:latest`.

We can re-use a lot of what we've done for `contour` in that case. I'll start work on a PR.

**Comment by youngnick** [comment]
So, I'll also bring in:
- image labels
- multiarch images
- latest tagging support

I'll only bring the `main` workflow in for now, I'll wait until we're closer to `v1alpha` for that.

**Comment by stevesloka** [comment]
Remaining tasks here are to build & push an image based upon new tags created in the repo. We should be able to copy bits from the Contour repo to solve this as well.

**Comment by skriss** [comment]
> Remaining tasks here are to build & push an image based upon new tags created in the repo. We should be able to copy bits from the Contour repo to solve this as well.

See:
- https://github.com/projectcontour/contour/blob/main/.github/workflows/build_tag.yaml
- https://github.com/projectcontour/contour/blob/main/hack/actions/build-and-push-release-images.sh
- https://github.com/projectcontour/contour/blob/main/Makefile#L18-L27
- https://github.com/projectcontour/contour/blob/main/Makefile#L103-L112

I think that covers most of it.

**Comment by danehans** [comment]
https://github.com/projectcontour/contour/blob/main/Makefile#L18-L27 and https://github.com/projectcontour/contour/blob/main/Makefile#L103-L112  were implemented by https://github.com/projectcontour/contour-operator/pull/83.
