### ISSUE TITLE
Support Pluralized xDS Version in Contour Config

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#85]
**Please describe the problem you have**
When https://github.com/projectcontour/contour/issues/3047 is fixed (targeting v1.11), `xds-server-version` will become `xds-server-versions`. Update the [configmap](https://github.com/projectcontour/contour/blob/main/examples/contour/01-contour-config.yaml) to support the pluralization with "v2" being the default and "v3" being a conditional option. Example:
```
server:
    xds-server-type: contour
    xds-server-versions:     # <--- change to "versions"
    - v2                               # <--- any in the list will be served
    - v3
```

**Comment by danehans** [comment]
Targeting v1alpha1 since https://github.com/projectcontour/contour/issues/3047 is targeted for v1.11. If this target is pushed out, so will this issue.

**Comment by stevesloka** [comment]
We ended up removing this option from the Contour config file with the idea being that Contour will decide which versions to serve. In 1.9 it's only v2, in 1.10, its both v2 & v3, in 1.11, it will be only v3. 

Given that, I think this issue can be closed.

**Comment by danehans** [comment]
Closed due to https://github.com/projectcontour/contour-operator/issues/85#issuecomment-724886073
