### ISSUE TITLE
Build & Push image GH Action is Failing

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour-operator#97]
The github action which pushes a `:main` tag on each merge to `main` branch is failing: 

![image](https://user-images.githubusercontent.com/1048184/98017003-ab55e880-1dcc-11eb-8472-f3d6daba4430.png)

@youngnick you hold all the keys to the bot account, can you double check those creds?

**Comment by youngnick** [comment]
Thanks @stevesloka, I reset the username and password, all working now.
